# Site wide configuration

title: "[ Zombies Reimagined ]"
description: A Critical Discourse Analysis of Popular Culture
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: http://ds.swarthmore.edu/zombies-reimagined
# url: 
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Swarthmore College Library Digital Scholarship
  email: digitalscholarship@swarthmore.edu
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: logo-mccabe-web.png # 160x160 px image for author byline
  disqus-shortname:

# prose.io front matter settings

prose:
  rooturl: '_posts/articles'
  media: 'images'
  metadata:
    _posts/articles:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter your title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "author"
        field:
          element: "hidden"
          value: "group5"
      - name: "group_members"
        field:
          element: "text"
          label: "Group members"
          value: ""
      - name: "modified"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "image_teaser"
        field:
          element: "hidden"
          value: ""
      - name: "storymap_id"
        field:
          element: "text"
          label: "Storymap ID"
          placeholder: "example: 772f6677de9353fe75919801ec1cb48b"
          help: "If including a Storymap, enter the string of characters included in your Storymap project URL"
          value: ""
      - name: "storymap_title"
        field:
          element: "text"
          label: "Storymap title"
          placeholder: "example: zombies-and-the-spread-of-fear"
          help: "If including a Storymap, enter the title associated with your Storymap project"
          value: ""
      - name: "timeline_id"
        field:
          element: "text"
          label: "Timeline ID"
          placeholder: "example: 1uGjhA8mK551YwHW1wRF5sh1utOxDV73JfuJbILe2jOI"
          help: "If including a Timeline, enter the string of characters included in your Timelinejs project URL"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish?"
          help: "Check the box when ready to publish"
          value: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - vendor
